### ISSUE TITLE
finalize/adjust raised exception

### ISSUE THREAD

**Issue by sparre-consafe** [yaml/AdaYaml#1]
I get this error when running `yaml-to_events` (even before entering data):
```
$ ./yaml-to_events

Execution terminated by unhandled exception
raised PROGRAM_ERROR : yaml-to_events.adb:11 finalize/adjust raised exception
Call stack traceback locations:
0x402ce5 0x4030f6 0x403c66 0x7faeeb4d0b43 0x402b7a 0xfffffffffffffffe
$ 
```
The executable was built with GNAT GPL 2017 (20170515-63).

The compilation flags (as indicated by `gprbuild -v`):
```
/opt/gnat/gpl_2017_x64/bin/gcc -c -x ada -gnatA -g -gnatoU -gnat2012 -O0 -funwind-tables -fstack-check -gnata -gnatw.d -gnaty2efhkM250 -gnatwla -gnatw.w -gnatec=/tmp/GNAT-TEMP-000004.TMP -gnatem=/tmp/GNAT-TEMP-000005.TMP /home/sattmate/svn/yaml_to_ada/source/web_api/yaml-to_events.adb
```

**Comment by sparre-consafe** [comment]
The same program works fine on AIX.  The AIX compiler is 32 bit, while the Linux one mentioned in the bug report is 64 bit.

The compiler flags have an added `-mminimal-toc`, but seem to be identical otherwise:
```
/usr2/tools/gnat/7.4.2w/bin/gcc -c -x ada -gnatA -g -gnatoU -gnat2012 -O0 -funwind-tables -fstack-check -gnata -gnatw.d -gnaty2efhkM250 -gnatwla -gnatw.w -mminimal-toc -gnatec=/tmp/GNAT-TEMP-000001.TMP -gnatem=/tmp/GNAT-TEMP-000002.TMP /usr2/branches/dkjacan_web_api/source/web_api/yaml-to_events.adb
```

**Comment by sparre-consafe** [comment]
The initial error occurred on Debian/Jessie.

**Comment by sparre-consafe** [comment]
Line numbers for the stack trace:

```
yaml-to_events.adb:?
/home/sattmate/svn/yaml_to_ada/source/web_api/yaml-to_events.adb:28 (discriminator 1)
/home/sattmate/svn/yaml_to_ada/target/adalib/global_gpr/inventor/web_api/b__yaml-to_events.adb:406
??:0
??:?
??:0
```

`b__yaml-to_events.adb:406` is the procedure call `Ada_Main_Program`, so that isn't very informative.

**Comment by sparre-consafe** [comment]
I've tried both `gdb` and plain old instrumentation to localise the bug.  The closest I've come so far is this:

```
$ ./yaml-to_events 
Exception STORAGE_ERROR (stack overflow or erroneous memory access) in YAML.Lexer.Finish.

Execution terminated by unhandled exception
raised PROGRAM_ERROR : yaml-to_events.adb:11 finalize/adjust raised exception
Call stack traceback locations:
0x402ce5 0x4030f6 0x403c66 0x7f636b074b43 0x402b7a 0xfffffffffffffffe
$ addr2line -e ./yaml-to_events 0x402ce5 0x4030f6 0x403c66 0x7f636b074b43 0x402b7a 0xfffffffffffffffe
yaml-to_events.adb:?
/home/sattmate/svn/yaml_to_ada/source/web_api/yaml-to_events.adb:28 (discriminator 1)
/home/sattmate/svn/yaml_to_ada/target/adalib/global_gpr/inventor/web_api/b__yaml-to_events.adb:406
??:0
??:?
??:0
$ 
```

The instrumentation used:
```
--- yaml-lexer.adb	(revision 36191)
+++ yaml-lexer.adb	(working copy)
@@ -2,6 +2,8 @@
 --  released under the terms of the MIT license, see the file "copying.txt"
 
 with Ada.Unchecked_Deallocation;
+with Ada.Exceptions;
+with Ada.Text_IO;
 with Yaml.Lexer.Evaluation;
 
 package body Yaml.Lexer is
@@ -140,6 +142,11 @@
       if L.Input /= null then
          Free (L.Input);
       end if;
+   exception
+      when E : others =>
+         Ada.Text_IO.Put_Line (File => Ada.Text_IO.Standard_Error,
+                               Item => "Exception " & Ada.Exceptions.Exception_Name (E) & " (" & Ada.Exceptions.Exception_Message (E) & ") in YAML.Lexer.Finish.");
+	 raise;
    end Finish;
 
    -----------------------------------------------------------------------------
```

I can't see how that can happen, but it is what I get. :-(

**Comment by sparre-consafe** [comment]
I have experimented with the differences between the compiler flags used on my project and internally in AdaYaml.  Omitting the flag "-gnata" (which is what enables Ada 2012 contract checks) on the "Text" library works around the issue on Debian/Jessie with GNAT GPL 2017.

**Comment by flyx** [comment]
That's very informative. I am afraid I don't have time to code this weekend, but with that information, I may be able to figure out what goes wrong without being able to reproduce it.

**Comment by sparre-consafe** [comment]
If you put

    pragma Assertion_Policy (Check);

in the beginning of all the `Text` packages (or add "-gnata" to the compiler flags in the project file in the "text" directory), I expect that you will be able to replicate the issue on a 64 bit Linux.

**Comment by flyx** [comment]
With that, I was able to reproduce the bug on macOS. For a reason I do not understand, in before the `begin` of `To_Events`, `Finalize` is called on a `Parser.Instance`, which calls the Lexer's `Finish` procedure you mentioned. This then somehow leads to the `Constraint_Error`, but I did not localize that yet – however, I am certain that the problem occurs because `Init` has not been called on the `Parser.Instance` object yet (it gets called in both `Set_Input` procedures).

As experiment, I restructured the code to make the `Set_Input` procedures constructor functions that return the `Parser.Instance`. This still lead to `Finalize` being called on an uninitialized object; however, the exception is no longer catchable in `Lexer.Finish`; instead, it occurs in `Parser.Finalize`.

Sadly, I cannot locate the reason for the `Constraint_Error` easily because using gdb with an exception breakpoint leads to a segfault. I tried using `-gnateE` to generate additional exception information to retrieve with `Ada.Exceptions.Exception_Information`, but it does not seem to work.

I might retry on another OS which may behave differently.

**Comment by sparre-consafe** [comment]
Is there any chance that the lack of `Initialize` procedures is the cause of the problem?

**Comment by flyx** [comment]
Good idea, but moving the `Init` code of the parser into an overriding `Initialize` does not fix the bug. I get the impression I am searching on the wrong end. Since the bug only happens with `-gnata` on the `Parser_Text` project, I will track down the precondition that fails by selectively deleting them.
